[package]
name = "ICPwallet"
version = "0.1.0"
edition = "2021"

[dependencies]
ic-cdk = "0.6.0"
ic-cdk-macros = "0.6.0"
candid = "0.8.0"
serde = "1.0"
serde_derive = "1.0"

[lib]
crate-type = ["cdylib"]